import React, { createContext, useState, useContext, useEffect } from "react";

type Language = "en" | "tr";

interface LanguageContextType {
	language: Language;
	setLanguage: (lang: Language) => void;
	t: (key: string) => string;
}

const translations = {
	en: {
		"app.title": "Campus Book Swap",
		"nav.browse": "Current Listings",
		"nav.my_books": "My Books",
		"nav.my_listings": "My Listings",
		"nav.swaps": "Swaps",
		"nav.messages": "Messages",
		"nav.logout": "Logout",
		"nav.login": "Login",
		"nav.register": "Register",
		"nav.admin": "Admin Panel",
		"browse.title": "Current Listings",
		"browse.welcome": "Welcome back, {name}!",
		"browse.welcome_guest": "Welcome to Campus Book Swap!",
		"browse.subtitle":
			"Find the textbooks you need or pass yours on to the next student.",
		"browse.search_placeholder": "Search by title, author, ISBN...",
		"browse.all_conditions": "All Conditions",
		"browse.all_departments": "All Departments",
		"browse.filter_price_min": "Min Price",
		"browse.filter_price_max": "Max Price",
		"browse.sort_by": "Sort By",
		"browse.sort_newest": "Newest First",
		"browse.sort_oldest": "Oldest First",
		"browse.sort_price_low": "Price: Low to High",
		"browse.sort_price_high": "Price: High to Low",
		"browse.clear_filters": "Clear Filters",
		"browse.no_books": "No books found",
		"browse.try_adjusting": "Try adjusting your search terms or filters.",
		"browse.empty_library":
			"The library is currently empty. Be the first to add a book!",
		"browse.add_btn": "Add a Book",
		"browse.favorites_only": "My Favorites", // Added
		"my_books.title": "My Books",
		"my_listings.title": "My Listings",
		"my_listings.empty": "You have no active listings.",
		"my_books.add_new": "Add New Book",
		"my_books.empty": "You haven't listed any books yet.",
		"my_books.list_first": "List your first book now",
		"my_books.active": "Active Listings",
		"my_books.history": "History",
		"my_books.show_listings": "Show active listings",
		"btn.details": "Details",
		"btn.edit": "Edit",
		"btn.delete": "Delete",
		"btn.relist": "Relist",
		"book.photo": "Book Photo",
		"book.title": "Title",
		"book.author": "Author",
		"book.isbn": "ISBN",
		"book.condition": "Condition",
		"book.edition": "Edition",
		"book.course": "Course",
		"book.department": "Department",
		"book.description": "Description",
		"book.for_sale": "For Sale",
		"book.for_swap": "Available for Swap",
		"book.price": "Price",
		"book.seller": "Seller",
		"book.type": "Type",
		"book.status": "Status",
		"btn.save_book": "Save Book",
		"btn.save_changes": "Save Changes",
		"btn.saving": "Saving...",
		"btn.mark_sold": "Mark as Sold",
		"btn.mark_swapped": "Mark as Swapped",
		"btn.archive": "Archive",
		"btn.unarchive": "Unarchive (Make Available)",
		"alert.fill_required":
			"Please fill in Title, Author, and upload a Book Photo.",
		"alert.file_too_large": "File is too large (Max 5MB).",
		"error.timeout":
			"Request timed out. Please check your internet connection or try a smaller image.",
		"swaps.title": "My Swaps",
		"swaps.clean_history": "Clean History",
		"swaps.refresh": "Refresh List",
		"swaps.incoming": "Incoming Requests",
		"swaps.outgoing": "Sent Requests",
		"swaps.empty_incoming": "No incoming swap requests.",
		"swaps.empty_outgoing": "You haven't sent any swap requests yet.",
		"swaps.you_give": "YOU GIVE",
		"swaps.you_get": "YOU GET",
		"swaps.from": "From:",
		"swaps.to": "To:",
		"swaps.status_pending": "Pending",
		"swaps.status_accepted": "Accepted",
		"swaps.status_rejected": "Rejected",
		"swaps.status_expired": "Expired (Unseen)",
		"btn.accept": "Accept",
		"btn.reject": "Reject",
		"btn.chat": "Chat",
		"modal.message_owner": "Message Owner",
		"modal.offer_swap": "Offer Swap",
		"modal.login_contact": "Log in to contact the owner",
		"modal.your_listing": "This is your book listing.",
		"modal.your_inventory": "This is your inventory item.",
		"btn.list_on_marketplace": "List on Marketplace",
		"swap_modal.title": "Offer a Swap",
		"swap_modal.requesting": "You are requesting:",
		"swap_modal.give_label": "Which book will you give?",
		"swap_modal.select_placeholder": "-- Select a book --",
		"swap_modal.no_books": "You have no books marked for swap. Add one first!",
		"swap_modal.message_label": "Message (Optional)",
		"swap_modal.message_placeholder": "Hi! I'd like to trade...",
		"btn.cancel": "Cancel",
		"btn.send_offer": "Send Offer",
		"chat.placeholder": "Type a message...",
		"chat.send": "Send",
		"chat.select_chat": "Select a chat to start messaging",
		"chat.card.interested": "I am interested in",
		"chat.card.view_details": "View Details",
		"chat.report": "Report User",
		"chat.report_title": "Report User",
		"chat.block": "Block User",
		"chat.report_reason": "Reason for reporting",
		"chat.report_placeholder": "Please describe the issue...",
		"chat.report_submit": "Submit Report",
		"chat.report_success": "User reported successfully.",
		"chat.block_confirm":
			"Are you sure you want to block this user? You will no longer receive messages from them.",
		"chat.block_success": "User blocked successfully.",
		"chat.blocked_error":
			"Message could not be sent. You have blocked this user or they have blocked you.",
		"chat.requests": "Message Requests",
		"chat.messages": "Messages",
		"chat.request_message": "{user} wants to send you a message.",
		"chat.accept": "Accept",
		"chat.decline": "Decline",
		"chat.pending_info": "You must accept this request to reply.",
		"location.error_denied":
			"Location permission denied. Please allow location access.",
		"location.error_unavailable":
			"Location unavailable. Please ensure GPS is enabled.",
		"location.error_timeout": "Location request timed out. Please try again.",
		"location.error_unsupported":
			"Geolocation is not supported by your browser.",

		// Status Translations
		"status.Available": "Available",
		"status.Requested": "Requested",
		"status.Reserved": "Reserved",
		"status.Swapped": "Swapped",
		"status.Sold": "Sold",
		"status.Archived": "Archived",

		// Condition Translations
		"condition.New": "New",
		"condition.Like New": "Like New",
		"condition.Very Good": "Very Good",
		"condition.Good": "Good",
		"condition.Acceptable": "Acceptable",

		// Department Translations
		"dept.Computer Engineering": "Computer Engineering",
		"dept.Electrical & Electronics Engineering":
			"Electrical & Electronics Engineering",
		"dept.Mechanical Engineering": "Mechanical Engineering",
		"dept.Industrial Engineering": "Industrial Engineering",
		"dept.Civil Engineering": "Civil Engineering",
		"dept.Architecture": "Architecture",
		"dept.Business Administration": "Business Administration",
		"dept.Economics": "Economics",
		"dept.Psychology": "Psychology",
		"dept.Law": "Law",
		"dept.Medicine": "Medicine",
		"dept.Dentistry": "Dentistry",
		"dept.Education": "Education",
		"dept.Mathematics": "Mathematics",
		"dept.Physics": "Physics",
		"dept.Chemistry": "Chemistry",
		"dept.Biology": "Biology",
		"dept.History": "History",
		"dept.Literature": "Literature",
		"dept.Sociology": "Sociology",
		"dept.Political Science": "Political Science",
		"dept.International Relations": "International Relations",
		"dept.Art & Design": "Art & Design",
		"dept.Communication": "Communication",
		"dept.Software Engineering": "Software Engineering",
		"dept.Other": "Other",
		"dept.General": "General",

		// Admin Translations
		"admin.title": "Admin Dashboard",
		"admin.tab.users": "Users",
		"admin.tab.reports": "Reports",
		"admin.tab.messages": "Inbox",
		"admin.col.username": "Username",
		"admin.col.university": "University",
		"admin.col.actions": "Actions",
		"admin.col.reporter": "Reporter",
		"admin.col.reported": "Reported User",
		"admin.col.reason": "Reason",
		"admin.col.date": "Date",
		"admin.col.name": "Name",
		"admin.col.email": "Email",
		"admin.col.subject": "Subject",
		"admin.col.message": "Message",
		"admin.btn.reset_pass": "Reset Password",
		"admin.btn.dismiss": "Dismiss",
		"admin.modal.edit_title": "Edit User",
		"admin.label.username": "Username",
		"admin.label.university": "University",
		"admin.label.new_pass": "New Password (Optional)",
		"admin.save_changes": "Save Changes",
		"admin.confirm_delete":
			"Are you sure you want to delete this user? This will remove all their books and chats.",
		"admin.self_delete_error": "You cannot delete yourself!",

		// Reg & Login Translations
		"reg.firstName": "First Name",
		"reg.lastName": "Last Name",
		"reg.email": "Email",
		"reg.phone": "Phone",
		"reg.password": "Password",
		"login.password": "Password",
		"login.forgot_password": "Forgot password?",

		// Profile Translations
		"profile.title": "My Profile",
		"profile.personal_info": "Personal Information",
		"profile.security": "Security",
		"profile.role": "Role",
		"profile.update_btn": "Update Profile",
		"profile.success": "Profile updated successfully!",
		"profile.new_pass_placeholder": "Leave blank to keep current password",
		"profile.old_pass": "Current Password",
		"profile.confirm_pass": "Confirm New Password",
		"profile.passwords_do_not_match": "New passwords do not match!",
		"profile.change_photo": "Change Photo",
		"profile.remove_photo": "Remove Photo",
		"profile.remove_photo_confirm":
			"Are you sure you want to remove your profile photo?",
		"profile.public.listings": "{name}'s Listings",
		"profile.public.empty": "No books listed by this user.",
		"profile.reviews": "Reviews",
		"profile.average_rating": "Average Rating",
		"profile.no_reviews": "No reviews yet.",
		"profile.add_review": "Leave a Review",
		"profile.rating_label": "Your Rating",
		"profile.comment_label": "Comment",
		"profile.submit_review": "Submit Review",

		// Footer & Static Pages
		"footer.about": "About Us",
		"footer.privacy": "Privacy Policy",
		"footer.contact": "Contact Us",
		"footer.rights": "All rights reserved.",
		"footer.desc": "Connecting students, one book at a time.",

		"about.title": "About Campus Book Swap",
		"about.mission": "Our Mission",
		"about.mission_text":
			"Campus Book Swap is designed to make education more affordable and sustainable. We connect students within the same campus to swap, buy, and sell textbooks easily.",
		"about.how_it_works": "How It Works",
		"about.step1": "List your old textbooks.",
		"about.step2": "Search for books you need.",
		"about.step3": "Chat, swap, or meet up on campus!",

		"privacy.title": "Privacy Policy",
		"privacy.intro":
			"We value your privacy. This policy explains how we handle your data.",
		"privacy.data_collection": "Data Collection",
		"privacy.data_text":
			"We only collect necessary information (name, email, campus info) to facilitate book swaps.",
		"privacy.security": "Security",
		"privacy.security_text":
			"Your data is stored securely and never sold to third parties.",

		"contact.title": "Contact Us",
		"contact.admin_email_label": "Admin Support Email",
		"contact.form_name": "Your Name",
		"contact.form_email": "Your Email",
		"contact.form_subject": "Subject / Type",
		"contact.form_message": "Message",
		"contact.type_suggestion": "Suggestion",
		"contact.type_complaint": "Complaint",
		"contact.type_feedback": "Feedback",
		"contact.type_other": "Other",
		"contact.btn_send": "Send Message",
		"contact.success": "Message sent! We will get back to you soon.",
	},
	tr: {
		"app.title": "Kampüs Kitap Takas",
		"nav.browse": "Güncel İlanlar",
		"nav.my_books": "Kitaplarım",
		"nav.my_listings": "İlanlarım",
		"nav.swaps": "Takaslar",
		"nav.messages": "Mesajlar",
		"nav.logout": "Çıkış",
		"nav.login": "Giriş",
		"nav.register": "Kayıt Ol",
		"nav.admin": "Admin Paneli",
		"browse.title": "Güncel İlanlar",
		"browse.welcome": "Tekrar hoş geldin, {name}!",
		"browse.welcome_guest": "Kampüs Kitap Takas'a Hoş Geldiniz!",
		"browse.subtitle":
			"Ders kitaplarını bul veya seninkini yeni bir öğrenciye devret.",
		"browse.search_placeholder": "Başlık, yazar veya ISBN ile ara...",
		"browse.all_conditions": "Tüm Durumlar",
		"browse.all_departments": "Tüm Bölümler",
		"browse.filter_price_min": "Min Fiyat",
		"browse.filter_price_max": "Max Fiyat",
		"browse.sort_by": "Sıralama",
		"browse.sort_newest": "En Yeni",
		"browse.sort_oldest": "En Eski",
		"browse.sort_price_low": "Fiyat: Düşükten Yükseğe",
		"browse.sort_price_high": "Fiyat: Yüksekten Düşüğe",
		"browse.clear_filters": "Filtreleri Temizle",
		"browse.no_books": "Kitap bulunamadı",
		"browse.try_adjusting":
			"Arama terimlerini veya filtreleri değiştirmeyi deneyin.",
		"browse.empty_library": "Kütüphane şu an boş. İlk kitabı sen ekle!",
		"browse.add_btn": "Kitap Ekle",
		"browse.favorites_only": "Sadece Favorilerim", // Added
		"my_books.title": "Kitaplarım",
		"my_listings.title": "İlanlarım",
		"my_listings.empty": "Aktif ilanınız yok.",
		"my_books.add_new": "Yeni Kitap Ekle",
		"my_books.empty": "Henüz hiç kitap listelemedin.",
		"my_books.list_first": "İlk kitabını şimdi listele",
		"my_books.active": "Aktif İlanlar",
		"my_books.history": "Geçmiş",
		"my_books.show_listings": "Aktif İlanları Göster",
		"btn.details": "Detaylar",
		"btn.edit": "Düzenle",
		"btn.delete": "Sil",
		"btn.relist": "Tekrar Listele",
		"book.photo": "Kitap Fotoğrafı",
		"book.title": "Başlık",
		"book.author": "Yazar",
		"book.isbn": "ISBN",
		"book.condition": "Durum",
		"book.edition": "Baskı",
		"book.course": "Ders",
		"book.department": "Bölüm",
		"book.description": "Açıklama",
		"book.for_sale": "Satılık",
		"book.for_swap": "Takasa Uygun",
		"book.price": "Fiyat",
		"book.seller": "Satıcı",
		"book.type": "Tür",
		"book.status": "Durum",
		"btn.save_book": "Kitabı Kaydet",
		"btn.save_changes": "Değişiklikleri Kaydet",
		"btn.saving": "Kaydediliyor...",
		"btn.mark_sold": "Satıldı İşaretle",
		"btn.mark_swapped": "Takaslandı İşaretle",
		"btn.archive": "Arşivle",
		"btn.unarchive": "Arşivden Çıkar (Aktif Et)",
		"alert.fill_required":
			"Lütfen Başlık, Yazar ve Kitap Fotoğrafı alanlarını doldurun.",
		"alert.file_too_large": "Dosya boyutu çok büyük (Max 5MB).",
		"error.timeout":
			"İstek zaman aşımına uğradı. Lütfen internet bağlantınızı kontrol edin veya daha küçük bir resim deneyin.",
		"swaps.title": "Takaslarım",
		"swaps.clean_history": "Geçmişi Temizle",
		"swaps.refresh": "Yenile",
		"swaps.incoming": "Gelen İstekler",
		"swaps.outgoing": "Giden İstekler",
		"swaps.empty_incoming": "Gelen takas isteği yok.",
		"swaps.empty_outgoing": "Henüz bir takas isteği göndermedin.",
		"swaps.you_give": "VERECEĞİN",
		"swaps.you_get": "ALACAĞIN",
		"swaps.from": "Kimden:",
		"swaps.to": "Kime:",
		"swaps.status_pending": "Beklemede",
		"swaps.status_accepted": "Kabul Edildi",
		"swaps.status_rejected": "Reddedildi",
		"swaps.status_expired": "Süresi Doldu",
		"btn.accept": "Kabul Et",
		"btn.reject": "Reddet",
		"btn.chat": "Sohbet",
		"modal.message_owner": "İlan Sahibine Mesaj",
		"modal.offer_swap": "Takas Teklif Et",
		"modal.login_contact": "İletişime geçmek için giriş yapın",
		"modal.your_listing": "Bu sizin kendi ilanınız.",
		"modal.your_inventory": "Bu sizin envanter öğeniz.",
		"btn.list_on_marketplace": "İlan Ver",
		"swap_modal.title": "Takas Teklifi",
		"swap_modal.requesting": "İstediğin kitap:",
		"swap_modal.give_label": "Hangi kitabını vereceksin?",
		"swap_modal.select_placeholder": "-- Bir kitap seç --",
		"swap_modal.no_books":
			"Takas için işaretlenmiş kitabın yok. Önce bir tane ekle!",
		"swap_modal.message_label": "Mesaj (Opsiyonel)",
		"swap_modal.message_placeholder": "Merhaba! Takas yapmak istiyorum...",
		"btn.cancel": "İptal",
		"btn.send_offer": "Teklifi Gönder",
		"chat.placeholder": "Bir mesaj yaz...",
		"chat.send": "Gönder",
		"chat.select_chat": "Mesajlaşmaya başlamak için bir sohbet seçin",
		"chat.card.interested": "İlgileniyorum:",
		"chat.card.view_details": "Detayları Gör",
		"chat.report": "Kullanıcıyı Raporla",
		"chat.report_title": "Kullanıcıyı Raporla",
		"chat.block": "Kullanıcıyı Engelle",
		"chat.report_reason": "Raporlama sebebi",
		"chat.report_placeholder": "Lütfen sorunu açıklayın...",
		"chat.report_submit": "Raporu Gönder",
		"chat.report_success": "Kullanıcı başarıyla raporlandı.",
		"chat.block_confirm":
			"Bu kullanıcıyı engellemek istediğinize emin misiniz? Artık ondan mesaj alamayacaksınız.",
		"chat.block_success": "Kullanıcı başarıyla engellendi.",
		"chat.blocked_error":
			"Mesaj gönderilemedi. Bu kullanıcıyı engellediniz veya o sizi engelledi.",
		"chat.requests": "Mesaj İstekleri",
		"chat.messages": "Mesajlar",
		"chat.request_message": "{user} sana mesaj göndermek istiyor.",
		"chat.accept": "Kabul Et",
		"chat.decline": "Reddet",
		"chat.pending_info": "Cevap yazabilmek için bu isteği kabul etmelisiniz.",
		"location.error_denied":
			"Konum izni reddedildi. Lütfen konum erişimine izin verin.",
		"location.error_unavailable":
			"Konum bulunamadı. GPS'inizin açık olduğundan emin olun.",
		"location.error_timeout":
			"Konum isteği zaman aşımına uğradı. Lütfen tekrar deneyin.",
		"location.error_unsupported":
			"Tarayıcınız konum servislerini desteklemiyor.",

		// Status Translations
		"status.Available": "Müsait",
		"status.Requested": "Talep Edildi",
		"status.Reserved": "Rezerve",
		"status.Swapped": "Takaslandı",
		"status.Sold": "Satıldı",
		"status.Archived": "Arşivlendi",

		// Condition Translations
		"condition.New": "Yeni",
		"condition.Like New": "Yeni Gibi",
		"condition.Very Good": "Çok İyi",
		"condition.Good": "İyi",
		"condition.Acceptable": "İdare Eder",

		// Department Translations
		"dept.Computer Engineering": "Bilgisayar Mühendisliği",
		"dept.Electrical & Electronics Engineering":
			"Elektrik Elektronik Mühendisliği",
		"dept.Mechanical Engineering": "Makine Mühendisliği",
		"dept.Industrial Engineering": "Endüstri Mühendisliği",
		"dept.Civil Engineering": "İnşaat Mühendisliği",
		"dept.Architecture": "Mimarlık",
		"dept.Business Administration": "İşletme",
		"dept.Economics": "Ekonomi",
		"dept.Psychology": "Psikoloji",
		"dept.Law": "Hukuk",
		"dept.Medicine": "Tıp",
		"dept.Dentistry": "Diş Hekimliği",
		"dept.Education": "Eğitim",
		"dept.Mathematics": "Matematik",
		"dept.Physics": "Fizik",
		"dept.Chemistry": "Kimya",
		"dept.Biology": "Biyoloji",
		"dept.History": "Tarih",
		"dept.Literature": "Edebiyat",
		"dept.Sociology": "Sosyoloji",
		"dept.Political Science": "Siyaset Bilimi",
		"dept.International Relations": "Uluslararası İlişkiler",
		"dept.Art & Design": "Sanat & Tasarım",
		"dept.Communication": "İletişim",
		"dept.Software Engineering": "Yazılım Mühendisliği",
		"dept.Other": "Diğer",
		"dept.General": "Genel",

		// Admin Translations
		"admin.title": "Yönetici Paneli",
		"admin.tab.users": "Kullanıcılar",
		"admin.tab.reports": "Raporlar",
		"admin.tab.messages": "Gelen Kutusu",
		"admin.col.username": "Kullanıcı Adı",
		"admin.col.university": "Üniversite",
		"admin.col.actions": "İşlemler",
		"admin.col.reporter": "Raporlayan",
		"admin.col.reported": "Raporlanan",
		"admin.col.reason": "Sebep",
		"admin.col.date": "Tarih",
		"admin.col.name": "İsim",
		"admin.col.email": "E-posta",
		"admin.col.subject": "Konu",
		"admin.col.message": "Mesaj",
		"admin.btn.reset_pass": "Şifre Sıfırla",
		"admin.btn.dismiss": "Sil",
		"admin.modal.edit_title": "Kullanıcı Düzenle",
		"admin.label.username": "Kullanıcı Adı",
		"admin.label.university": "Üniversite",
		"admin.label.new_pass": "Yeni Şifre (İsteğe Bağlı)",
		"admin.save_changes": "Değişiklikleri Kaydet",
		"admin.confirm_delete":
			"Bu kullanıcıyı silmek istediğinize emin misiniz? Bu işlem tüm kitaplarını ve sohbetlerini silecektir.",
		"admin.self_delete_error": "Kendinizi silemezsiniz!",

		// Reg & Login Translations
		"reg.firstName": "Ad",
		"reg.lastName": "Soyad",
		"reg.email": "E-posta",
		"reg.phone": "Telefon",
		"reg.password": "Şifre",
		"login.password": "Şifre",
		"login.forgot_password": "Şifremi unuttum?",

		// Profile Translations
		"profile.title": "Profilim",
		"profile.personal_info": "Kişisel Bilgiler",
		"profile.security": "Güvenlik",
		"profile.role": "Rol",
		"profile.update_btn": "Profili Güncelle",
		"profile.success": "Profil başarıyla güncellendi!",
		"profile.new_pass_placeholder": "Mevcut şifreyi korumak için boş bırakın",
		"profile.old_pass": "Mevcut Şifre",
		"profile.confirm_pass": "Yeni Şifreyi Onayla",
		"profile.passwords_do_not_match": "Yeni şifreler eşleşmiyor!",
		"profile.change_photo": "Fotoğrafı Değiştir",
		"profile.remove_photo": "Fotoğrafı Kaldır",
		"profile.remove_photo_confirm":
			"Profil fotoğrafını kaldırmak istediğine emin misin?",
		"profile.public.listings": "{name} İlanları",
		"profile.public.empty": "Bu kullanıcının listelediği kitap yok.",
		"profile.reviews": "Değerlendirmeler",
		"profile.average_rating": "Ortalama Puan",
		"profile.no_reviews": "Henüz değerlendirme yok.",
		"profile.add_review": "Değerlendirme Yap",
		"profile.rating_label": "Puanınız",
		"profile.comment_label": "Yorum",
		"profile.submit_review": "Gönder",

		// Footer & Static Pages
		"footer.about": "Hakkımızda",
		"footer.privacy": "Gizlilik Politikası",
		"footer.contact": "İletişim",
		"footer.rights": "Tüm hakları saklıdır.",
		"footer.desc": "Öğrencileri kitaplarla buluşturuyoruz.",

		"about.title": "Kampüs Kitap Takas Hakkında",
		"about.mission": "Misyonumuz",
		"about.mission_text":
			"Kampüs Kitap Takas, eğitimi daha ulaşılabilir ve sürdürülebilir kılmak için tasarlandı. Aynı kampüsteki öğrencilerin ders kitaplarını kolayca takas etmesini, alıp satmasını sağlıyoruz.",
		"about.how_it_works": "Nasıl Çalışır?",
		"about.step1": "Eski ders kitaplarını listele.",
		"about.step2": "İhtiyacın olan kitapları ara.",
		"about.step3": "Sohbet et, takas yap veya kampüste buluş!",

		"privacy.title": "Gizlilik Politikası",
		"privacy.intro":
			"Gizliliğinize önem veriyoruz. Bu politika verilerinizi nasıl işlediğimizi açıklar.",
		"privacy.data_collection": "Veri Toplama",
		"privacy.data_text":
			"Sadece kitap takasını gerçekleştirmek için gerekli olan bilgileri (isim, e-posta, iletişim bilgileri) topluyoruz.",
		"privacy.security": "Güvenlik",
		"privacy.security_text":
			"Verileriniz güvenli bir şekilde saklanır ve asla üçüncü taraflara satılmaz.",

		"contact.title": "Bize Ulaşın",
		"contact.admin_email_label": "Yönetici Destek E-postası",
		"contact.form_name": "Adınız",
		"contact.form_email": "E-posta Adresiniz",
		"contact.form_subject": "Konu / Tür",
		"contact.form_message": "Mesajınız",
		"contact.type_suggestion": "Öneri",
		"contact.type_complaint": "Şikayet",
		"contact.type_feedback": "Geri Bildirim",
		"contact.type_other": "Diğer",
		"contact.btn_send": "Mesaj Gönder",
		"contact.success":
			"Mesajınız gönderildi! En kısa sürede size dönüş yapacağız.",
	},
};

const LanguageContext = createContext<LanguageContextType>(null!);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
	children,
}) => {
	const [language, setLanguage] = useState<Language>("tr");

	useEffect(() => {
		const storedLang = localStorage.getItem("lang") as Language;
		if (storedLang) setLanguage(storedLang);
	}, []);

	const handleSetLanguage = (lang: Language) => {
		setLanguage(lang);
		localStorage.setItem("lang", lang);
	};

	const t = (key: string): string => {
		return (translations[language] as any)[key] || key;
	};

	return (
		<LanguageContext.Provider
			value={{ language, setLanguage: handleSetLanguage, t }}
		>
			{children}
		</LanguageContext.Provider>
	);
};

export const useLanguage = () => useContext(LanguageContext);
