export const DEPARTMENTS = [
    "Architecture",
    "Art & Design",
    "Biology",
    "Business Administration",
    "Chemistry",
    "Civil Engineering",
    "Communication",
    "Computer Engineering",
    "Dentistry",
    "Economics",
    "Education",
    "Electrical & Electronics Engineering",
    "History",
    "Industrial Engineering",
    "International Relations",
    "Law",
    "Literature",
    "Mathematics",
    "Mechanical Engineering",
    "Medicine",
    "Physics",
    "Political Science",
    "Psychology",
    "Sociology",
    "Software Engineering",
    "Other"
];
